### ISSUE TITLE
Add Windows binary

### ISSUE THREAD

**Issue by mrx23dot** [raspberrypi/picotool#143] opened 2024-09-11 12:48 UTC
Even if it's not the latest.

Building on Windows is a nightmare.

**Comment by lurch** [comment] 2024-09-11 13:32
Duplicate of #135 :wink:

**Comment by will-v-pi** [comment] 2024-09-18 16:41
Yep - see https://github.com/raspberrypi/pico-sdk-tools

**Closed by will-v-pi** 2024-09-18 16:41 UTC
