### ISSUE TITLE
"Unable to Connect" Windows built with mingw

### ISSUE THREAD

**Issue by JeffersonDing** [raspberrypi/picotool#36] opened 2021-08-01 16:47 UTC
Hi,
I am having this same issue even after installing the `libusb-win32` driver to `RP2 Boot (Interface 1)` using `Zadig`. Any ideas on whats the issue here?
I used `mingw32-make` to build the executable and it seems to work just fine, but just cannot connect to the pico board.

_Originally posted by @JeffersonDing in https://github.com/raspberrypi/picotool/issues/20#issuecomment-890285833_

**Comment by mcuee** [comment] 2022-07-13 06:28
Duplicate of #20.
And in turn duplicate of
* https://github.com/raspberrypi/picoprobe/issues/3

Solution is to use latest libusb-1.0 version 1.0.26 or use WinUSB driver.

**Closed** 2022-07-13 08:18 UTC
