### ISSUE TITLE
Error saving all flash rom

### ISSUE THREAD

**Issue by mardini1974** [raspberrypi/picotool#94] opened 2024-02-12 11:48 UTC
Hello, When I try to save all flash from the pico, it disconnects from BOOTSEL mode and I get an error.

![image](https://github.com/raspberrypi/picotool/assets/17930620/c5c18cde-ae15-4b86-b301-777dab9ee69b)

I have to disconnect the pico and set it back to BOOTSEL mode, while I can save a program  (-p) without any problem.
i'm working in Windows WSL2 ubuntu, using usbipd to [connect USB device to ubuntu ](https://devblogs.microsoft.com/commandline/connecting-usb-devices-to-wsl/)

**Comment by lurch** [comment] 2024-02-12 12:11
This may not be relevant to your problem, but I think if your Pico is already in BOOTSEL mode, then there's no need to use the `-F` option of picotool?

**Comment by mardini1974** [comment] 2024-02-12 14:00
> This may not be relevant to your problem, but I think if your Pico is already in BOOTSEL mode, then there's no need to use the `-F` option of picotool?

I tried both with Force and without force, both are the same.

**Comment by mardini1974** [comment] 2024-02-13 21:43
Hi Kilograham, I fried the first Raspberry Pi PICO due to a faulty connection, but I did the test on a new PICOs and it worked correctly I could copy the RAM from one to the other, So the problem maybe in WSL or USBipd, The challenge in installing the binary on my work computer give some issues with IT security!, I do prefer building the application on WSL.

**Comment by will-v-pi** [comment] 2024-07-29 11:15
I've tried this on the latest WSL2 version (2.2.4) with the latest usbipd (4.2.0) and am unable to reproduce this issue - could you try updating to the latest versions and check if it still occurs?

**Comment by will-v-pi** [comment] 2024-08-28 16:36
Closing this for now, as I can't reproduce it - feel free to reopen if you're still having this issue

**Closed by will-v-pi** 2024-08-28 16:36 UTC
